### ISSUE TITLE
Task Results Extension

### ISSUE THREAD

**Issue by GeoffHook** [BusinessProcessSimulation/BPSim#1]
V1 doesn't support sufficient parameters for holding results for a Task, e.g. both number started and number completed

![capture](https://cloud.githubusercontent.com/assets/10026215/5245093/e6ab509c-794e-11e4-8c5a-51a1edb511da.PNG)

**Comment by ldugan** [comment]
I found this useful as well, and can show how I used there extensions.

**Comment by SimonRinguette** [comment]
At the face to face meeting in montreal (July 2016) we decided to modify the semantic of the triggerCount count request from the number of times traversed to number of times triggered (started). Section 8.2

We also modified the definition of a count request on a time parameter to the number of times that the interval completed. Section 8.1

This is to address the use case: Number of activities started vs number of activities completed.

The count on processing time of an activity is the number of instance completed and the count of triggerCount is the number of instance started.
