### ISSUE TITLE
Synchronizing triggering parameters for an exclusive multiple event start

### ISSUE THREAD

**Issue by ldugan** [BusinessProcessSimulation/BPSim#11]
I want to be able to set up trigger parameters (inter-trigger and counts) to occur within some kind of collective constraint that holds to a distributed occurrence pattern across the multiple events.  At the moment, I as the modeler must hand-jam this and hope for the best.

**Comment by SimonRinguette** [comment]
At the face to face meeting in montreal (July 2016) we agreed that this issue is already covered in the spec with a triggerCount on an initiating Event Based Gateways
