### ISSUE TITLE
Enabling differentiated treatment of tokens to mimic case-like behavior (similar to instance matching)

### ISSUE THREAD

**Issue by ldugan** [BusinessProcessSimulation/BPSim#12]
Doing a lot of work in bending BPMN to do case mgmt, and would like to explore how BPSim could help in simulating the desired operational behaviors. I realize that this is somewhat vague, but I also need help in trying to describe it. I have developed approached to modeling that could start the conversation.

**Comment by ldugan** [comment]
Doing a lot of work in bending BPMN to do case mgmt, and would like to explore how BPSim could help in simulating the desired operational behaviors.  I realize that this is somewhat vague, but I also need help in trying to describe it.  I have developed approached to modeling that could start the conversation.

**Comment by SimonRinguette** [comment]
At the face to face meeting in montreal (July 2016) we agreed that this would get resolved with the resource selection issue #6.
