### ISSUE TITLE
Reporting queue sizes at activities as "tokens waiting for resource"

### ISSUE THREAD

**Issue by ldugan** [BusinessProcessSimulation/BPSim#13]
Some sim/mod vendors with their own sim language show queue sizes as a proxy indicator for backlog.  BPSim, to my knowledge, does not have this covered.  When pressed with the need to report it for a client, Lanner & Trisotech gave me the vendor extension below to use, which was very helpful.  I would like BPSim to address this need ASAP.  The results set returned by this is the max, min, and mean of queue size as understood as # of tokens waiting for a resource.

                         <VendorExtension name="l-sim-task-results-v1">
                            ...
                            <lsim:MaximumNumberOfTokensWaitingForResource>
                                <ResultRequest>max</ResultRequest>
                            </lsim:MaximumNumberOfTokensWaitingForResource>
                            <lsim:MinimumNumberOfTokensWaitingForResource>
                                <ResultRequest>min</ResultRequest>
                            </lsim:MinimumNumberOfTokensWaitingForResource>
                            <lsim:AverageNumberOfTokensWaitingForResource>
                                <ResultRequest>mean</ResultRequest>
                            </lsim:AverageNumberOfTokensWaitingForResource>
                            <lsim:MaximumNumberOfResourcesUsed>
                                <ResultRequest>max</ResultRequest>
                            ...
                        </VendorExtension>

**Comment by SimonRinguette** [comment]
At the face to face meeting in montreal (July 2016) we have decided to add a property parameter called queueLength for query only
