### ISSUE TITLE
Results Extension - Process

### ISSUE THREAD

**Issue by GeoffHook** [BusinessProcessSimulation/BPSim#2]
Extra results are useful at a Process level
![capture](https://cloud.githubusercontent.com/assets/10026215/5245115/50b75292-794f-11e4-9b0b-9ee17c6082d3.PNG)

**Comment by ldugan** [comment]
Absolutely need this.

**Comment by SimonRinguette** [comment]
At the face to face meeting in montreal (July 2016) we have decided to add a new chapter (9) to add both time and work in progress reporting.

We also decided to deprecate the currency overload in the floating parameter

**Comment by SimonRinguette** [comment]
At the face to face meeting in montreal (July 2016) we have decided reverse the chapter 9 (it never existed) and instead add the possibility to request results at the process and sub-process level for time, cost and control parameters in certain cases.
