### ISSUE TITLE
Latest BPSim 2.0 spec document with minor updates

### ISSUE THREAD

**Issue by jhorgan** [BusinessProcessSimulation/BPSim#23]
Attached is a version of the BPSim 2.0 specification, with minor markups following the face-to-face meeting in July 2016. This need to be integrated to the master document. 

[BPSim v2.0-1.docx](https://github.com/BusinessProcessSimulation/BPSim/files/533654/BPSim.v2.0-1.docx)

**Comment by SimonRinguette** [comment]
Jeremy will apply those corrections to the anotated version of the spec

**Comment by SimonRinguette** [comment]
Jeremy applied those corrections
