### ISSUE TITLE
Warmup Period

### ISSUE THREAD

**Issue by GeoffHook** [BusinessProcessSimulation/BPSim#3]
A warm up period is considered important in most simulation software products. This allows the model to be run from empty for a period, results collection reset, then run on. This provides results based on periods when the system is 'primed', as is normal in industrial or business processes.

This would be a scenario parameter very similar to Duration.

**Comment by ldugan** [comment]
See comment on initialization.

**Comment by SimonRinguette** [comment]
At the face to face meeting in montreal (July 2016) we have decided to add a warmup period attribute to scenario pareters

**Comment by SimonRinguette** [comment]
At the face to face meeting in montreal (July 2016) we have decided to add a type to the properties of Property Parameter that points to a new enumeration of possible types.
