### ISSUE TITLE
Results collection - time based

### ISSUE THREAD

**Issue by GeoffHook** [BusinessProcessSimulation/BPSim#4]
Simulation results are often required time dependent, for example number of jobs completed per hour.
A possible extension of V1 would be to allow a calendar to be attached to a result request, with an additional control parameter defining if the statistic should be reset.

For example an hourly recording of output could be either for each hour or cumulative by hour.

**Comment by GeoffHook** [comment]
After closer investigation of the likely user needs and implementation, I am thinking that a single calendar e.g. daily,  across all elements in the model to control results collection is preferable. 
This could be simply controlled as a scenario parameter in BPSIM, controlling the frequency and the resetting of all results being collected. Current result requests expressed at element, parameter level would be unchanged. At the interval controlled by scenario parameter all result requests would be actioned.

**Comment by jeremyhorgan** [comment]
For example: 
![resultrequesttime](https://cloud.githubusercontent.com/assets/8865282/6352770/02934ea0-bc3d-11e4-8e8b-f6bbae486bea.PNG)

**Comment by SimonRinguette** [comment]
At the face to face meeting in montreal (July 2016) we have decided to add a baseResultFrequency and baseResultFrequencyCumul to Scenario Parameters. We have also added a resultTimeStamp in ParameterValue
