### ISSUE TITLE
Token Trace

### ISSUE THREAD

**Issue by GeoffHook** [BusinessProcessSimulation/BPSim#5]
We have found it useful to output a token trace from the simulation. This is useful for validation and deeper analysis. Due to the fact that this can slow down simulation execution and potentially create a very large output file this has been implemented selectively in a vendor extension at Task level
![capture](https://cloud.githubusercontent.com/assets/10026215/5245238/bb874a90-7950-11e4-9ad3-7c8505f611be.PNG)
.

**Comment by SimonRinguette** [comment]
As discussed on the January 28th 2015 meeting, it would be interesting to consider an existing trace standard like either: BPAF (http://www.wfmc.org/standards/bpaf) or XES (http://www.xes-standard.org/)

**Comment by jeremyhorgan** [comment]
Example output:
Scenario	Replication	TokenId	Element	Arrived			Started			Completed		Resources
scenario_1	0		0	Task1	2015-02-24 15:38:45	2015-02-24 15:38:45	2015-02-24 15:48:45	
scenario_1	0		1	Task1	2015-02-24 15:39:45	2015-02-24 15:39:45	2015-02-24 15:49:45	
scenario_1	0		2	Task1	2015-02-24 15:40:45	2015-02-24 15:40:45	2015-02-24 15:50:45	
scenario_1	0		3	Task1	2015-02-24 15:41:45	2015-02-24 15:41:45	2015-02-24 15:51:45	
scenario_1	0		4	Task1	2015-02-24 15:42:45	2015-02-24 15:42:45	2015-02-24 15:52:45

**Comment by SimonRinguette** [comment]
At the face to face meeting in montreal (July 2016) we have decided to add two Simulation Parameter (traceFormat and TraceOutput) to allow the output of XES traces
