### ISSUE TITLE
PropertyParameters - no way to specifying the type of Property

### ISSUE THREAD

**Issue by jhorgan** [BusinessProcessSimulation/BPSim#7]
Currently there is no way to specify the type of Property (int, double, string etc.) used during property value assignment. 

The Car Repair Process example that is part of the Implementers Guide, uses the following to assign a value to the "noOfIssues" property. The "noOfIssues" property is intended to be an integer count value. However the TruncatedNormalDistribution will return a double precision value between 1 and 1000, for example: 3.565534.
```
<bpsim:PropertyParameters>
  <bpsim:Property name="noOfIssues">
      <bpsim:TruncatedNormalDistribution max="1000" mean="2" min="1" standardDeviation="1"/>
   </bpsim:Property>
</bpsim:PropertyParameters>
```

The logic in the model decrements the "noOfIssues" each time an issue is repaired. Having fixed an issue, the number of issues now remaining is now 2.565534 (3.565534 - 1)

The gateway which decides if there are more issue to be fixed uses the logic getProperty('noOfIssues') = 0. 

Clearly, unless we are very luck we will never reach exactly zero.

Here are some possible solutions:

- Give a hint during property assignment as to what the expected expression type is e.g.
```
<bpsim:PropertyParameters>
  <bpsim:Property name="noOfIssues" **type="int"**>
      <bpsim:TruncatedNormalDistribution max="1000" mean="2" min="1" standardDeviation="1"/>
   </bpsim:Property>
</bpsim:PropertyParameters>
```
Possibly make this an optional attribute?

- Declare somewhere in the ```<ScenarioParameters>``` or  at the ```<ElementParameters>``` what the type of each property is.

**Comment by SimonRinguette** [comment]
During Feb 18th webmeeting, i have suggested to fix this issue using a less than operator and publish a new version of the implementers guide (1.0.2) which I just did

**Comment by jhorgan** [comment]
Could we reopen this for BPSim 1.1?

**Comment by SimonRinguette** [comment]
At the face to face meeting in montreal (July 2016) we have decided to add a type to the properties of Property Parameter that points to a new enumeration of possible types.
